# libpq.po
#   Japanese message translation file for libpq
#
# Copyright (C) 2011-2024 PostgreSQL Global Development Group
#
# This file is distributed under the same license as the PostgreSQL package.
#
msgid ""
msgstr ""
<<<<<<< HEAD
"Project-Id-Version: PostgreSQL 10\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2019-11-09 09:19+0000\n"
"PO-Revision-Date: 2018-08-21 21:01+0900\n"
"Last-Translator: Kyotaro Horiguchi <horiguchi.kyotaro@lab.ntt.co.jp>\n"
"Language-Team: jpug-doc <jpug-doc@ml.postgresql.jp>\n"
=======
"Project-Id-Version: libpq (PostgreSQL 17)\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2024-06-14 11:23+0900\n"
"PO-Revision-Date: 2024-06-14 11:34+0900\n"
"Last-Translator: Kyotaro Horiguchi <horikyota.ntt@gmail.com>\n"
"Language-Team: Japan PostgreSQL Users Group <jpug-doc@ml.postgresql.jp>\n"
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
<<<<<<< HEAD
"X-Generator: Poedit 1.5.4\n"

#: fe-auth-scram.c:189
msgid "malformed SCRAM message (empty message)\n"
msgstr "SCRAMメッセージのフォーマット異常 (空のメッセージ)\n"

#: fe-auth-scram.c:195
msgid "malformed SCRAM message (length mismatch)\n"
msgstr "SCRAMメッセージのフォーマット異常 (長さの不整合)\n"

#: fe-auth-scram.c:244
msgid "incorrect server signature\n"
msgstr "正しくないサーバ署名\n"

#: fe-auth-scram.c:253
msgid "invalid SCRAM exchange state\n"
msgstr "不正なSCRAM交換状態\n"

#: fe-auth-scram.c:276
#, c-format
msgid "malformed SCRAM message (attribute \"%c\" expected)\n"
msgstr "SCRAMメッセージのフォーマット異常 (属性 \"%c\" が必要)\n"

#: fe-auth-scram.c:285
#, c-format
msgid "malformed SCRAM message (expected character \"=\" for attribute \"%c\")\n"
msgstr "SCRAMメッセージのフォーマット異常 (属性 \"%c\" に文字 \"=\" が必要)\n"

#: fe-auth-scram.c:326
msgid "could not generate nonce\n"
msgstr "nonce を生成できませんでした\n"

#: fe-auth-scram.c:334 fe-auth-scram.c:401 fe-auth-scram.c:523
#: fe-auth-scram.c:543 fe-auth-scram.c:569 fe-auth-scram.c:583
#: fe-auth-scram.c:632 fe-auth-scram.c:666 fe-auth.c:227 fe-auth.c:362
#: fe-auth.c:432 fe-auth.c:467 fe-auth.c:653 fe-auth.c:812 fe-auth.c:1124
#: fe-auth.c:1272 fe-connect.c:835 fe-connect.c:1264 fe-connect.c:1440
#: fe-connect.c:1922 fe-connect.c:1945 fe-connect.c:2606 fe-connect.c:4152
#: fe-connect.c:4404 fe-connect.c:4523 fe-connect.c:4777 fe-connect.c:4857
#: fe-connect.c:4956 fe-connect.c:5212 fe-connect.c:5241 fe-connect.c:5313
#: fe-connect.c:5337 fe-connect.c:5355 fe-connect.c:5456 fe-connect.c:5465
#: fe-connect.c:5821 fe-connect.c:5971 fe-exec.c:2705 fe-exec.c:3452
#: fe-exec.c:3617 fe-lobj.c:895 fe-protocol2.c:1213 fe-protocol3.c:999
#: fe-protocol3.c:1685 fe-secure-common.c:110 fe-secure-openssl.c:438
#: fe-secure-openssl.c:1025
msgid "out of memory\n"
msgstr "メモリ不足\n"

#: fe-auth-scram.c:561
msgid "invalid SCRAM response (nonce mismatch)\n"
msgstr "不正なSCRAM応答 (nonce の不一致)\n"

#: fe-auth-scram.c:592
#, fuzzy
#| msgid "malformed SCRAM message (invalid server signature)\n"
msgid "malformed SCRAM message (invalid salt)\n"
msgstr "SCRAMメッセージのフォーマット異常 (不正なサーバ署名)\n"

#: fe-auth-scram.c:606
msgid "malformed SCRAM message (invalid iteration count)\n"
msgstr "SCRAMメッセージのフォーマット異常 (不正な繰り返し回数)\n"

#: fe-auth-scram.c:612
msgid "malformed SCRAM message (garbage at end of server-first-message)\n"
msgstr "SCRAMメッセージのフォーマット異常 (server-first-message 終端の余分なデータ)\n"

#: fe-auth-scram.c:643
#, c-format
msgid "error received from server in SCRAM exchange: %s\n"
msgstr "SCRAM交換中にサーバからのエラーを受信しました: %s\n"

#: fe-auth-scram.c:659
msgid "malformed SCRAM message (garbage at end of server-final-message)\n"
msgstr "SCRAMメッセージのフォーマット異常 (server-final-message 終端の余分なデータ)\n"

#: fe-auth-scram.c:677
msgid "malformed SCRAM message (invalid server signature)\n"
msgstr "SCRAMメッセージのフォーマット異常 (不正なサーバ署名)\n"

#: fe-auth.c:122
#, c-format
msgid "out of memory allocating GSSAPI buffer (%d)\n"
msgstr "GSSAPIバッファの割り当ての際のメモリ不足(%d)\n"

#: fe-auth.c:177
msgid "GSSAPI continuation error"
msgstr "GSSAI続行エラー"

#: fe-auth.c:207 fe-auth.c:461 fe-secure-common.c:98
msgid "host name must be specified\n"
msgstr "ホスト名を指定しなければなりません\n"

#: fe-auth.c:214
msgid "duplicate GSS authentication request\n"
msgstr "重複するGSS認証要求\n"

#: fe-auth.c:240
msgid "GSSAPI name import error"
msgstr "GSSAPI名のインポートエラー"

#: fe-auth.c:303
#, c-format
msgid "out of memory allocating SSPI buffer (%d)\n"
msgstr "SSPIバッファの割り当ての際のメモリ不足(%d)\n"

#: fe-auth.c:351
msgid "SSPI continuation error"
msgstr "SSPI続行エラー"

#: fe-auth.c:422
msgid "duplicate SSPI authentication request\n"
msgstr "重複するSSPI認証要求\n"

#: fe-auth.c:447
msgid "could not acquire SSPI credentials"
msgstr "SSPI資格を入手できませんでした"

#: fe-auth.c:501
msgid "duplicate SASL authentication request\n"
msgstr "重複するSASL認証要求\n"

#: fe-auth.c:559
msgid "server offered SCRAM-SHA-256-PLUS authentication over a non-SSL connection\n"
msgstr "サーバが非SSL接続上で SCRAM-SHA-256-PLUS 認証を提示してきました\n"

#: fe-auth.c:571
msgid "none of the server's SASL authentication mechanisms are supported\n"
msgstr "サーバ側のいずれのSASL認証機構もサポートされていません\n"

#: fe-auth.c:677
#, c-format
msgid "out of memory allocating SASL buffer (%d)\n"
msgstr "SASLバッファの割り当ての際のメモリ不足(%d)\n"

#: fe-auth.c:702
msgid "AuthenticationSASLFinal received from server, but SASL authentication was not completed\n"
msgstr "サーバからAuthenticationSASLFinalを受信しました、しかしSASL認証は完了していません\n"

#: fe-auth.c:779
msgid "SCM_CRED authentication method not supported\n"
msgstr "SCM_CRED認証方式はサポートされていません\n"

#: fe-auth.c:870
msgid "Kerberos 4 authentication not supported\n"
msgstr "Kerberos 4認証はサポートされていません\n"

#: fe-auth.c:875
msgid "Kerberos 5 authentication not supported\n"
msgstr "Kerberos 5認証はサポートされていません\n"

#: fe-auth.c:946
msgid "GSSAPI authentication not supported\n"
msgstr "GSSAPI認証はサポートされていません\n"

#: fe-auth.c:978
msgid "SSPI authentication not supported\n"
msgstr "SSPI認証はサポートされていません\n"

#: fe-auth.c:986
msgid "Crypt authentication not supported\n"
msgstr "Crypt認証はサポートされていません\n"

#: fe-auth.c:1052
=======
"X-Generator: Poedit 1.8.13\n"

#: ../../port/user.c:43 ../../port/user.c:79
#, c-format
msgid "could not look up local user ID %d: %s"
msgstr "ローカルユーザーID %dの参照に失敗しました: %s"

#: ../../port/user.c:48 ../../port/user.c:84
#, c-format
msgid "local user with ID %d does not exist"
msgstr "ID %d を持つローカルユーザーは存在しません"

#: fe-auth-scram.c:223
#, c-format
msgid "malformed SCRAM message (empty message)"
msgstr "SCRAMメッセージのフォーマット異常 (空のメッセージ)"

#: fe-auth-scram.c:228
#, c-format
msgid "malformed SCRAM message (length mismatch)"
msgstr "SCRAMメッセージのフォーマット異常 (長さの不整合)"

#: fe-auth-scram.c:272
#, c-format
msgid "could not verify server signature: %s"
msgstr "サーバー署名を検証できませんでした: %s"

#: fe-auth-scram.c:278
#, c-format
msgid "incorrect server signature"
msgstr "正しくないサーバー署名"

#: fe-auth-scram.c:287
#, c-format
msgid "invalid SCRAM exchange state"
msgstr "不正なSCRAM交換状態"

#: fe-auth-scram.c:311
#, c-format
msgid "malformed SCRAM message (attribute \"%c\" expected)"
msgstr "SCRAMメッセージのフォーマット異常 (属性 \"%c\" が必要)"

#: fe-auth-scram.c:320
#, c-format
msgid "malformed SCRAM message (expected character \"=\" for attribute \"%c\")"
msgstr "SCRAMメッセージのフォーマット異常 (属性 \"%c\" に文字 \"=\" が必要)"

#: fe-auth-scram.c:360
#, c-format
msgid "could not generate nonce"
msgstr "nonce を生成できませんでした"

#: fe-auth-scram.c:369 fe-auth-scram.c:442 fe-auth-scram.c:594
#: fe-auth-scram.c:614 fe-auth-scram.c:638 fe-auth-scram.c:652
#: fe-auth-scram.c:698 fe-auth-scram.c:734 fe-auth-scram.c:908 fe-auth.c:296
#: fe-auth.c:369 fe-auth.c:403 fe-auth.c:618 fe-auth.c:727 fe-auth.c:1199
#: fe-auth.c:1362 fe-cancel.c:159 fe-connect.c:936 fe-connect.c:976
#: fe-connect.c:1860 fe-connect.c:2022 fe-connect.c:3430 fe-connect.c:4758
#: fe-connect.c:5070 fe-connect.c:5325 fe-connect.c:5443 fe-connect.c:5690
#: fe-connect.c:5770 fe-connect.c:5868 fe-connect.c:6119 fe-connect.c:6146
#: fe-connect.c:6222 fe-connect.c:6245 fe-connect.c:6269 fe-connect.c:6304
#: fe-connect.c:6390 fe-connect.c:6398 fe-connect.c:6755 fe-connect.c:6905
#: fe-exec.c:530 fe-exec.c:1315 fe-exec.c:3254 fe-exec.c:4234 fe-exec.c:4398
#: fe-gssapi-common.c:109 fe-lobj.c:870 fe-protocol3.c:209 fe-protocol3.c:232
#: fe-protocol3.c:255 fe-protocol3.c:272 fe-protocol3.c:293 fe-protocol3.c:369
#: fe-protocol3.c:737 fe-protocol3.c:976 fe-protocol3.c:1787
#: fe-protocol3.c:2187 fe-secure-common.c:110 fe-secure-gssapi.c:496
#: fe-secure-openssl.c:427 fe-secure-openssl.c:1277
#, c-format
msgid "out of memory"
msgstr "メモリ不足です"

#: fe-auth-scram.c:376
#, c-format
msgid "could not encode nonce"
msgstr "nonceをエンコードできませんでした"

#: fe-auth-scram.c:564
#, c-format
msgid "could not calculate client proof: %s"
msgstr "クライアント証明の算出に失敗しました: %s"

#: fe-auth-scram.c:579
#, c-format
msgid "could not encode client proof"
msgstr "クライアントの証明のエンコードに失敗しました"

#: fe-auth-scram.c:631
#, c-format
msgid "invalid SCRAM response (nonce mismatch)"
msgstr "不正なSCRAM応答 (nonce の不一致)"

#: fe-auth-scram.c:661
#, c-format
msgid "malformed SCRAM message (invalid salt)"
msgstr "SCRAMメッセージのフォーマット異常 (不正なソルト)"

#: fe-auth-scram.c:674
#, c-format
msgid "malformed SCRAM message (invalid iteration count)"
msgstr "SCRAMメッセージのフォーマット異常 (不正な繰り返し回数)"

#: fe-auth-scram.c:679
#, c-format
msgid "malformed SCRAM message (garbage at end of server-first-message)"
msgstr "SCRAMメッセージのフォーマット異常 (server-first-message 終端の余分なデータ)"

#: fe-auth-scram.c:713
#, c-format
msgid "error received from server in SCRAM exchange: %s"
msgstr "SCRAM交換中にサーバーからのエラーを受信しました: %s"

#: fe-auth-scram.c:728
#, c-format
msgid "malformed SCRAM message (garbage at end of server-final-message)"
msgstr "SCRAMメッセージのフォーマット異常 (server-final-message 終端の余分なデータ)"

#: fe-auth-scram.c:745
#, c-format
msgid "malformed SCRAM message (invalid server signature)"
msgstr "SCRAMメッセージのフォーマット異常 (不正なサーバー署名)"

#: fe-auth-scram.c:917
msgid "could not generate random salt"
msgstr "乱数ソルトを生成できませんでした"

#: fe-auth.c:77
#, c-format
msgid "out of memory allocating GSSAPI buffer (%d)"
msgstr "GSSAPIバッファの割り当ての際のメモリ不足(%d)"

#: fe-auth.c:138
msgid "GSSAPI continuation error"
msgstr "GSSAI続行エラー"

#: fe-auth.c:168 fe-auth.c:397 fe-gssapi-common.c:97 fe-secure-common.c:99
#: fe-secure-common.c:173
#, c-format
msgid "host name must be specified"
msgstr "ホスト名を指定しなければなりません"

#: fe-auth.c:174
#, c-format
msgid "duplicate GSS authentication request"
msgstr "重複するGSS認証要求"

#: fe-auth.c:238
#, c-format
msgid "out of memory allocating SSPI buffer (%d)"
msgstr "SSPIバッファの割り当ての際のメモリ不足(%d)"

#: fe-auth.c:285
msgid "SSPI continuation error"
msgstr "SSPI続行エラー"

#: fe-auth.c:359
#, c-format
msgid "duplicate SSPI authentication request"
msgstr "重複したSSPI認証要求"

#: fe-auth.c:384
msgid "could not acquire SSPI credentials"
msgstr "SSPI資格を入手できませんでした"

#: fe-auth.c:436
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "channel binding required, but SSL not in use"
msgstr "チャネルバインディングが要求されていますが、SSLが使用されていません"

<<<<<<< HEAD
#: fe-auth.c:1099
#, c-format
msgid "user name lookup failure: error code %lu\n"
msgstr "ユーザー名の検索に失敗: エラー コード %lu\n"

#: fe-auth.c:1109 fe-connect.c:2533
#, c-format
msgid "could not look up local user ID %d: %s\n"
msgstr "ローカルユーザID%dが見つかりませんでした: %s\n"

#: fe-auth.c:1114 fe-connect.c:2538
#, c-format
msgid "local user with ID %d does not exist\n"
msgstr "ID %d を持つローカルユーザは存在しません\n"

#: fe-auth.c:1216
msgid "unexpected shape of result set returned for SHOW\n"
msgstr "SHOW に対する予期しない形のリザルトセット\n"

#: fe-auth.c:1225
msgid "password_encryption value too long\n"
msgstr "password_encryptionの値が長すぎます\n"

#: fe-auth.c:1265
#, c-format
msgid "unrecognized password encryption algorithm \"%s\"\n"
msgstr "認識できないパスワード暗号化アルゴリズム \"%s\"\n"

#: fe-connect.c:1018
#, c-format
msgid "could not match %d host names to %d hostaddr values\n"
msgstr "%d個のホスト名と%d個のhostaddrの値との突き合せはできません\n"

#: fe-connect.c:1094
#, c-format
msgid "could not match %d port numbers to %d hosts\n"
msgstr "%d個のポート番号と%d個のホストとの突き合せはできません\n"

#: fe-connect.c:1190
#, c-format
msgid "invalid sslmode value: \"%s\"\n"
msgstr "sslmodeの値が不正です: \"%s\"\n"

#: fe-connect.c:1211
#, c-format
msgid "sslmode value \"%s\" invalid when SSL support is not compiled in\n"
msgstr "SSLサポートが組み込まれていない場合sslmodeの値\"%s\"は不正です\n"

#: fe-connect.c:1246
#, c-format
msgid "invalid target_session_attrs value: \"%s\"\n"
msgstr "target_session_attrsの値が不正です: \"%s\"\n"

#: fe-connect.c:1464
=======
#: fe-auth.c:442
#, c-format
msgid "duplicate SASL authentication request"
msgstr "重複するSASL認証要求"

#: fe-auth.c:500
#, c-format
msgid "channel binding is required, but client does not support it"
msgstr "チャネルバインディングが要求されていますが、クライアントがサポートしていません"

#: fe-auth.c:516
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "server offered SCRAM-SHA-256-PLUS authentication over a non-SSL connection"
msgstr "サーバーが非SSL接続上で SCRAM-SHA-256-PLUS 認証を提示してきました"

<<<<<<< HEAD
#: fe-connect.c:1494
=======
#: fe-auth.c:531
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "none of the server's SASL authentication mechanisms are supported"
msgstr "サーバー側のいずれのSASL認証機構もサポートされていません"

<<<<<<< HEAD
#: fe-connect.c:1552
=======
#: fe-auth.c:538
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "channel binding is required, but server did not offer an authentication method that supports channel binding"
msgstr "チャネルバインディングが要求されていますが、サーバーがチャネルバインディングをサポートする認証方式を提供しませんでした"

<<<<<<< HEAD
#: fe-connect.c:1561
=======
#: fe-auth.c:640
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "out of memory allocating SASL buffer (%d)"
msgstr "SASLバッファの割り当ての際のメモリ不足(%d)"

<<<<<<< HEAD
#: fe-connect.c:1612 fe-connect.c:1644 fe-connect.c:1677 fe-connect.c:2325
#, c-format
msgid "setsockopt(%s) failed: %s\n"
msgstr "setsockopt(%s)が失敗しました: %s\n"

#: fe-connect.c:1726
=======
#: fe-auth.c:663
#, c-format
msgid "AuthenticationSASLFinal received from server, but SASL authentication was not completed"
msgstr "サーバーからAuthenticationSASLFinalを受信しました、しかしSASL認証は完了していません"

#: fe-auth.c:673
#, c-format
msgid "no client response found after SASL exchange success"
msgstr "SASL交換の成功後にクライアントからの応答がありません"

#: fe-auth.c:736 fe-auth.c:743 fe-auth.c:1345 fe-auth.c:1356
#, c-format
msgid "could not encrypt password: %s"
msgstr "パスワードを暗号化できませんでした: %s"

#: fe-auth.c:771
msgid "server requested a cleartext password"
msgstr "サーバーが平文パスワードを要求してきました"

#: fe-auth.c:773
msgid "server requested a hashed password"
msgstr "サーバーがハッシュ化パスワードを要求してきました"

#: fe-auth.c:776
msgid "server requested GSSAPI authentication"
msgstr "サーバーがGSSAPI認証を要求してきました"

#: fe-auth.c:778
msgid "server requested SSPI authentication"
msgstr "サーバーがSSPI認証を要求してきました"

#: fe-auth.c:782
msgid "server requested SASL authentication"
msgstr "サーバーがSASL認証を要求してきました"

#: fe-auth.c:785
msgid "server requested an unknown authentication type"
msgstr "サーバーが不明な認証タイプを要求してきました"

#: fe-auth.c:818
#, c-format
msgid "server did not request an SSL certificate"
msgstr "サーバーがSSL証明書を要求してきませんでした"

#: fe-auth.c:823
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "server accepted connection without a valid SSL certificate"
msgstr "サーバーは有効なSSL証明書なしで接続を受け付けました"

<<<<<<< HEAD
#: fe-connect.c:2035
msgid "invalid connection state, probably indicative of memory corruption\n"
msgstr "接続状態が不正です。メモリ障害の可能性があります\n"

#: fe-connect.c:2101
#, c-format
msgid "invalid port number: \"%s\"\n"
msgstr "不正なポート番号です: \"%s\"\n"

#: fe-connect.c:2117
=======
#: fe-auth.c:877
msgid "server did not complete authentication"
msgstr "サーバーが認証を完了しませんでした"

#: fe-auth.c:911
#, c-format
msgid "authentication method requirement \"%s\" failed: %s"
msgstr "必須の認証方式\"%s\"が失敗しました: %s"

#: fe-auth.c:934
#, c-format
msgid "channel binding required, but server authenticated client without channel binding"
msgstr "チャネルバインディングが要求されていますが、サーバーはチャネルバインディングを使用せずに認証を行いました"

#: fe-auth.c:939
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "channel binding required but not supported by server's authentication request"
msgstr "チャネルバインディングが要求されていますが、サーバーの認証要求ではサポートされていません"

<<<<<<< HEAD
#: fe-connect.c:2130
#, c-format
msgid "could not parse network address \"%s\": %s\n"
msgstr "ネットワークアドレス\"%s\"をパースできませんでした: %s\n"

#: fe-connect.c:2143
#, c-format
msgid "Unix-domain socket path \"%s\" is too long (maximum %d bytes)\n"
msgstr "Unixドメインソケットのパス\"%s\"が長すぎます(最大 %d バイト)\n"

#: fe-connect.c:2158
=======
#: fe-auth.c:973
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "Kerberos 4 authentication not supported"
msgstr "Kerberos 4認証はサポートされていません"

<<<<<<< HEAD
#: fe-connect.c:2262
=======
#: fe-auth.c:977
#, c-format
msgid "Kerberos 5 authentication not supported"
msgstr "Kerberos 5認証はサポートされていません"

#: fe-auth.c:1047
#, c-format
msgid "GSSAPI authentication not supported"
msgstr "GSSAPI認証はサポートされていません"

#: fe-auth.c:1078
#, c-format
msgid "SSPI authentication not supported"
msgstr "SSPI認証はサポートされていません"

#: fe-auth.c:1085
#, c-format
msgid "Crypt authentication not supported"
msgstr "Crypt認証はサポートされていません"

#: fe-auth.c:1149
#, c-format
msgid "authentication method %u not supported"
msgstr "認証方式%uはサポートされていません"

#: fe-auth.c:1186
#, c-format
msgid "user name lookup failure: error code %lu"
msgstr "ユーザー名の参照に失敗: エラーコード %lu"

#: fe-auth.c:1308
#, c-format
msgid "unexpected shape of result set returned for SHOW"
msgstr "SHOW に対する予期しない形のリザルトセット"

#: fe-auth.c:1316
#, c-format
msgid "\"password_encryption\" value too long"
msgstr "\"password_encryption\"の値が長すぎます"

#: fe-auth.c:1366
#, c-format
msgid "unrecognized password encryption algorithm \"%s\""
msgstr "認識できないパスワード暗号化アルゴリズム \"%s\""

#: fe-cancel.c:76
#, c-format
msgid "connection pointer is NULL"
msgstr "接続ポインタはNULLです"

#: fe-cancel.c:82 fe-misc.c:572
#, c-format
msgid "connection not open"
msgstr "接続はオープンされていません"

#: fe-cancel.c:193
#, c-format
msgid "cancel request is already being sent on this connection"
msgstr "このセッションではすでにキャンセル要求を送出済みです"

#: fe-cancel.c:263
#, c-format
msgid "unexpected response from server"
msgstr "サーバーからの想定外の応答"

#: fe-connect.c:1182
#, c-format
msgid "could not match %d host names to %d hostaddr values"
msgstr "%d個のホスト名と%d個のhostaddrの値との突き合せはできません"

#: fe-connect.c:1262
#, c-format
msgid "could not match %d port numbers to %d hosts"
msgstr "%d個のポート番号と%d個のホストとの突き合せはできません"

#: fe-connect.c:1387
#, c-format
msgid "negative require_auth method \"%s\" cannot be mixed with non-negative methods"
msgstr "require_authの方式否定\"%s\"は方式要求と同時に指定することはできません"

#: fe-connect.c:1400
#, c-format
msgid "require_auth method \"%s\" cannot be mixed with negative methods"
msgstr "require_authの方式要求\"%s\"は方式否定と同時に指定することはできません"

#: fe-connect.c:1460 fe-connect.c:1511 fe-connect.c:1553 fe-connect.c:1596
#: fe-connect.c:1699 fe-connect.c:1745 fe-connect.c:1785 fe-connect.c:1806
#, c-format
msgid "invalid %s value: \"%s\""
msgstr "%s の値が不正: \"%s\""

#: fe-connect.c:1493
#, c-format
msgid "require_auth method \"%s\" is specified more than once"
msgstr "require_authで方式\"%s\"が複数回指定されました"

#: fe-connect.c:1534 fe-connect.c:1573 fe-connect.c:1605 fe-connect.c:1707
#, c-format
msgid "%s value \"%s\" invalid when SSL support is not compiled in"
msgstr "%s 値\"%s\"はSSLサポートがコンパイルされていない場合は無効です"

#: fe-connect.c:1625
#, c-format
msgid "weak sslmode \"%s\" may not be used with sslnegotiation=direct (use \"require\", \"verify-ca\", or \"verify-full\")"
msgstr "弱いsslmode\"%s\"はsslnegotiation=direct とともには使用できません( \"require\", \"verify-ca\"または\"verify-full\"を使用してください)"

#: fe-connect.c:1647
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "weak sslmode \"%s\" may not be used with sslrootcert=system (use \"verify-full\")"
msgstr "弱いsslmode\"%s\"はsslrootcert=systemとともには使用できません(\"verify-full\"を使用してください)"

<<<<<<< HEAD
#: fe-connect.c:2284
#, c-format
msgid "could not set socket to nonblocking mode: %s\n"
msgstr "ソケットを非ブロッキングモードに設定できませんでした: %s\n"

#: fe-connect.c:2294
=======
#: fe-connect.c:1660 fe-connect.c:1668
#, c-format
msgid "invalid \"%s\" value: \"%s\""
msgstr "\"%s\"の値が不正: \"%s\""

#: fe-connect.c:1685
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "invalid SSL protocol version range"
msgstr "不正なSSLプロトコルバージョン範囲"

<<<<<<< HEAD
#: fe-connect.c:2312
msgid "keepalives parameter must be an integer\n"
msgstr "keepaliveのパラメータは整数でなければなりません\n"

#: fe-connect.c:2450
=======
#: fe-connect.c:1722
#, c-format
msgid "%s value \"%s\" is not supported (check OpenSSL version)"
msgstr "%s 値\"%s\"はサポートされていません(OpenSSLのバージョンを確認してください)"

#: fe-connect.c:1752
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "gssencmode value \"%s\" invalid when GSSAPI support is not compiled in"
msgstr "gssencmodeの値\"%s\"はGSSAPIサポートがコンパイルされていない場合は不正"

<<<<<<< HEAD
#: fe-connect.c:2478
=======
#: fe-connect.c:2045
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not set socket to TCP no delay mode: %s"
msgstr "TCPソケットを非遅延モードに設定できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:2520
msgid "requirepeer parameter is not supported on this platform\n"
msgstr "このプラットフォームでは requirepeer パラメータはサポートされていません\n"

#: fe-connect.c:2523
=======
#: fe-connect.c:2104
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "connection to server on socket \"%s\" failed: "
msgstr "ソケット\"%s\"のサーバーへの接続に失敗しました: "

<<<<<<< HEAD
#: fe-connect.c:2546
=======
#: fe-connect.c:2130
#, c-format
msgid "connection to server at \"%s\" (%s), port %s failed: "
msgstr "\"%s\"(%s)、ポート%sのサーバーへの接続に失敗しました: "

#: fe-connect.c:2135
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "connection to server at \"%s\", port %s failed: "
msgstr "\"%s\"、ポート%sのサーバーへの接続に失敗しました: "

<<<<<<< HEAD
#: fe-connect.c:2580
=======
#: fe-connect.c:2158
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "\tIs the server running locally and accepting connections on that socket?"
msgstr "\tサーバーはローカルで稼働していてそのソケットで接続を受け付けていますか?"

<<<<<<< HEAD
#: fe-connect.c:2619
=======
#: fe-connect.c:2160
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "\tIs the server running on that host and accepting TCP/IP connections?"
msgstr "\tサーバーはそのホスト上で稼働していてTCP/IP接続を受け付けていますか?"

<<<<<<< HEAD
#: fe-connect.c:2689
msgid "server does not support SSL, but SSL was required\n"
msgstr "サーバはSSLをサポートしていませんが、SSLが要求されました\n"

#: fe-connect.c:2715
#, c-format
msgid "received invalid response to SSL negotiation: %c\n"
msgstr "SSL調停に対して不正な応答を受信しました: %c\n"

#: fe-connect.c:2792 fe-connect.c:2825
=======
#: fe-connect.c:2206 fe-connect.c:2240 fe-connect.c:2275 fe-connect.c:2373
#: fe-connect.c:3098
#, c-format
msgid "%s(%s) failed: %s"
msgstr "%s(%s)が失敗しました: %s"

#: fe-connect.c:2339
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s(%s) failed: error code %d"
msgstr "%s(%s)が失敗しました: エラーコード %d"

<<<<<<< HEAD
#: fe-connect.c:3052
msgid "unexpected message from server during startup\n"
msgstr "起動時にサーバから想定外のメッセージがありました\n"

#: fe-connect.c:3282
#, c-format
msgid "could not make a writable connection to server \"%s:%s\"\n"
msgstr "サーバ\"%s:%s\"への書き込み可能な接続を確立できませんでした\n"

#: fe-connect.c:3328
#, c-format
msgid "test \"SHOW transaction_read_only\" failed on server \"%s:%s\"\n"
msgstr "サーバ\"%s:%s\"で\"SHOW transaction_read_only\"のテストに失敗しました\n"

#: fe-connect.c:3343
#, c-format
msgid "invalid connection state %d, probably indicative of memory corruption\n"
msgstr "接続状態%dが不正です。メモリ障害の可能性があります\n"

#: fe-connect.c:3758 fe-connect.c:3818
=======
#: fe-connect.c:2650
#, c-format
msgid "invalid connection state, probably indicative of memory corruption"
msgstr "接続状態が不正です。メモリ障害の可能性があります"

#: fe-connect.c:2733
#, c-format
msgid "invalid port number: \"%s\""
msgstr "不正なポート番号です: \"%s\""

#: fe-connect.c:2747
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not translate host name \"%s\" to address: %s"
msgstr "ホスト名\"%s\"をアドレスに変換できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:4165
#, c-format
msgid "invalid LDAP URL \"%s\": scheme must be ldap://\n"
msgstr "不正なLDAP URL\"%s\":スキーマはldap://でなければなりません\n"

#: fe-connect.c:4180
#, c-format
msgid "invalid LDAP URL \"%s\": missing distinguished name\n"
msgstr "不正なLDAP URL \"%s\": 区別名がありません\n"

#: fe-connect.c:4191 fe-connect.c:4244
#, c-format
msgid "invalid LDAP URL \"%s\": must have exactly one attribute\n"
msgstr "不正なLDAP URL \"%s\": 正確に1つの属性を持たなければなりません\n"

#: fe-connect.c:4201 fe-connect.c:4258
#, c-format
msgid "invalid LDAP URL \"%s\": must have search scope (base/one/sub)\n"
msgstr "不正なLDAP URL \"%s\": 検索スコープ(base/one/sub)を持たなければなりません\n"

#: fe-connect.c:4212
#, c-format
msgid "invalid LDAP URL \"%s\": no filter\n"
msgstr "不正なLDAP URL \"%s\": フィルタがありません\n"

#: fe-connect.c:4233
#, c-format
msgid "invalid LDAP URL \"%s\": invalid port number\n"
msgstr "不正なLDAP URL \"%s\": ポート番号が不正です\n"

#: fe-connect.c:4267
msgid "could not create LDAP structure\n"
msgstr "LDAP構造体を作成できませんでした\n"

#: fe-connect.c:4343
=======
#: fe-connect.c:2759
#, c-format
msgid "could not parse network address \"%s\": %s"
msgstr "ネットワークアドレス\"%s\"をパースできませんでした: %s"

#: fe-connect.c:2770
#, c-format
msgid "Unix-domain socket path \"%s\" is too long (maximum %d bytes)"
msgstr "Unixドメインソケットのパス\"%s\"が長すぎます(最大 %d バイト)"

#: fe-connect.c:2784
#, c-format
msgid "could not translate Unix-domain socket path \"%s\" to address: %s"
msgstr "Unixドメインソケットのパス\"%s\"をアドレスに変換できませんでした: %s"

#: fe-connect.c:2950 fe-connect.c:4302
#, c-format
msgid "GSSAPI encryption required but it is not supported over a local socket"
msgstr "GSSAPI暗号化が要求されていますが、ローカルソケットではサポートされません"

#: fe-connect.c:2958 fe-connect.c:4431
#, c-format
msgid "GSSAPI encryption required but no credential cache"
msgstr "GSSAPI暗号化が要求されましたが、資格証明キャッシュがありません"

#: fe-connect.c:3026
#, c-format
msgid "could not create socket: %s"
msgstr "ソケットを作成できませんでした: %s"

#: fe-connect.c:3057
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not set socket to nonblocking mode: %s"
msgstr "ソケットを非ブロッキングモードに設定できませんでした: %s\\"

<<<<<<< HEAD
#: fe-connect.c:4354
msgid "more than one entry found on LDAP lookup\n"
msgstr "LDAP検索結果が複数ありました\n"

#: fe-connect.c:4355 fe-connect.c:4367
msgid "no entry found on LDAP lookup\n"
msgstr "LDAP検索結果が空でした\n"

#: fe-connect.c:4378 fe-connect.c:4391
msgid "attribute has no values on LDAP lookup\n"
msgstr "LDAP検索で属性に値がありませんでした\n"

#: fe-connect.c:4443 fe-connect.c:4462 fe-connect.c:4995
=======
#: fe-connect.c:3068
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not set socket to close-on-exec mode: %s"
msgstr "ソケットをclose-on-execモードに設定できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:4535 fe-connect.c:5180 fe-connect.c:5954
#, c-format
msgid "invalid connection option \"%s\"\n"
msgstr "接続オプション\"%s\"は不正です\n"

#: fe-connect.c:4551 fe-connect.c:5044
msgid "unterminated quoted string in connection info string\n"
msgstr "接続情報文字列において閉じていない引用符がありました\n"

#: fe-connect.c:4634
=======
#: fe-connect.c:3086
#, c-format
msgid "keepalives parameter must be an integer"
msgstr "keepaliveのパラメータは整数でなければなりません"

#: fe-connect.c:3225
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not get socket error status: %s"
msgstr "ソケットのエラー状態を取得できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:4657
=======
#: fe-connect.c:3252
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not get client address from socket: %s"
msgstr "ソケットからクライアントアドレスを取得できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:4672
=======
#: fe-connect.c:3278
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "requirepeer parameter is not supported on this platform"
msgstr "このプラットフォームでは requirepeer パラメータはサポートされていません"

<<<<<<< HEAD
#: fe-connect.c:4745 fe-connect.c:4789
=======
#: fe-connect.c:3280
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not get peer credentials: %s"
msgstr "接続先の資格証明を取得できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:4756
#, c-format
msgid "nested service specifications not supported in service file \"%s\", line %d\n"
msgstr "サービスファイル\"%s\"ではネストしたサービス指定はサポートされていません、行%d\n"

#: fe-connect.c:5476
#, c-format
msgid "invalid URI propagated to internal parser routine: \"%s\"\n"
msgstr "内部パーサ処理へ伝わった不正なURI: \"%s\"\n"

#: fe-connect.c:5553
=======
#: fe-connect.c:3293
#, c-format
msgid "requirepeer specifies \"%s\", but actual peer user name is \"%s\""
msgstr "requirepeerは\"%s\"を指定していますが、実際の接続先名は\"%s\"です"

#: fe-connect.c:3331
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not send GSSAPI negotiation packet: %s"
msgstr "GSSAPIネゴシエーションパケットを送信できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:5560
=======
#: fe-connect.c:3380
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not send SSL negotiation packet: %s"
msgstr "SSLネゴシエーションパケットを送信できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:5575
=======
#: fe-connect.c:3412
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not send cancel packet: %s"
msgstr "キャンセルパケットを送信できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:5704
=======
#: fe-connect.c:3442
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not send startup packet: %s"
msgstr "開始パケットを送信できませんでした: %s"

<<<<<<< HEAD
#: fe-connect.c:5724
#, c-format
msgid "missing key/value separator \"=\" in URI query parameter: \"%s\"\n"
msgstr "URI問い合わせパラメータ内にキーと値を分ける\\\"=\\\"がありません: \"%s\"\n"

#: fe-connect.c:5775
#, c-format
msgid "invalid URI query parameter: \"%s\"\n"
msgstr "不正なURI問い合わせパラメータ:\"%s\"\n"

#: fe-connect.c:5849
#, c-format
msgid "invalid percent-encoded token: \"%s\"\n"
msgstr "不正なパーセント符号化トークン: \"%s\"\n"

#: fe-connect.c:5859
=======
#: fe-connect.c:3509
msgid "server does not support SSL, but SSL was required"
msgstr "サーバーはSSLをサポートしていませんが、要求されています"

#: fe-connect.c:3528
#, c-format
msgid "received invalid response to SSL negotiation: %c"
msgstr "SSLネゴシエーションに対して不正な応答を受信しました: %c"

#: fe-connect.c:3556
#, c-format
msgid "received unencrypted data after SSL response"
msgstr "SSL応答の後に非暗号化データを受信しました"

#: fe-connect.c:3630
msgid "server doesn't support GSSAPI encryption, but it was required"
msgstr "サーバーがGSSAPI暗号化サポートしていませんが、要求されてます"

#: fe-connect.c:3634
#, c-format
msgid "received invalid response to GSSAPI negotiation: %c"
msgstr "GSSAPIネゴシエーションに対して不正な応答を受信しました: %c"

#: fe-connect.c:3652
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "received unencrypted data after GSSAPI encryption response"
msgstr "GSSAPI暗号化応答の後に非暗号化データを受信しました"

<<<<<<< HEAD
#: fe-connect.c:6205
msgid "connection pointer is NULL\n"
msgstr "接続ポインタはNULLです\n"

#: fe-connect.c:6503
=======
#: fe-connect.c:3708
#, c-format
msgid "expected authentication request from server, but received %c"
msgstr "サーバーからの認証要求を想定していましたが、%cを受信しました"

#: fe-connect.c:3736 fe-connect.c:3859
#, c-format
msgid "received invalid authentication request"
msgstr "不正な認証要求を受信しました"

#: fe-connect.c:3742 fe-connect.c:3844
#, c-format
msgid "received invalid protocol negotiation message"
msgstr "不正なプロトコルネゴシエーションメッセージを受信しました"

#: fe-connect.c:3761 fe-connect.c:3815
#, c-format
msgid "received invalid error message"
msgstr "不正なエラーメッセージを受信しました"

#: fe-connect.c:3930
#, c-format
msgid "unexpected message from server during startup"
msgstr "起動中にサーバーから想定外のメッセージがありました"

#: fe-connect.c:4021
#, c-format
msgid "session is read-only"
msgstr "セッションは読み取り専用です"

#: fe-connect.c:4023
#, c-format
msgid "session is not read-only"
msgstr "セッションは読み取り専用ではありません"

#: fe-connect.c:4076
#, c-format
msgid "server is in hot standby mode"
msgstr "サーバーはホットスタンバイモードです"

#: fe-connect.c:4078
#, c-format
msgid "server is not in hot standby mode"
msgstr "サーバーはスタンバイモードではありません"

#: fe-connect.c:4200 fe-connect.c:4250
#, c-format
msgid "\"%s\" failed"
msgstr "\"%s\"が失敗しました"

#: fe-connect.c:4264
#, c-format
msgid "invalid connection state %d, probably indicative of memory corruption"
msgstr "接続状態%dは不正です。メモリ障害の可能性があります"

#: fe-connect.c:5083
#, c-format
msgid "invalid LDAP URL \"%s\": scheme must be ldap://"
msgstr "不正なLDAP URL\"%s\":スキームはldap://でなければなりません"

#: fe-connect.c:5098
#, c-format
msgid "invalid LDAP URL \"%s\": missing distinguished name"
msgstr "不正なLDAP URL \"%s\": 識別名がありません"

#: fe-connect.c:5110 fe-connect.c:5168
#, c-format
msgid "invalid LDAP URL \"%s\": must have exactly one attribute"
msgstr "不正なLDAP URL \"%s\": ちょうど1つの属性を持たなければなりません"

#: fe-connect.c:5122 fe-connect.c:5184
#, c-format
msgid "invalid LDAP URL \"%s\": must have search scope (base/one/sub)"
msgstr "不正なLDAP URL \"%s\": 検索スコープ(base/one/sub)を持たなければなりません"

#: fe-connect.c:5134
#, c-format
msgid "invalid LDAP URL \"%s\": no filter"
msgstr "不正なLDAP URL \"%s\": フィルタがありません"

#: fe-connect.c:5156
#, c-format
msgid "invalid LDAP URL \"%s\": invalid port number"
msgstr "不正なLDAP URL \"%s\": ポート番号が不正です"

#: fe-connect.c:5193
#, c-format
msgid "could not create LDAP structure"
msgstr "LDAP構造体を作成できませんでした"

#: fe-connect.c:5268
#, c-format
msgid "lookup on LDAP server failed: %s"
msgstr "LDAPサーバーで検索に失敗しました: %s"

#: fe-connect.c:5278
#, c-format
msgid "more than one entry found on LDAP lookup"
msgstr "LDAP参照で複数のエントリが見つかりました"

#: fe-connect.c:5280 fe-connect.c:5291
#, c-format
msgid "no entry found on LDAP lookup"
msgstr "LDAP参照でエントリが見つかりません"

#: fe-connect.c:5301 fe-connect.c:5313
#, c-format
msgid "attribute has no values on LDAP lookup"
msgstr "LDAP参照で属性に値がありません"

#: fe-connect.c:5364 fe-connect.c:5383 fe-connect.c:5907
#, c-format
msgid "missing \"=\" after \"%s\" in connection info string"
msgstr "接続情報文字列において\"%s\"の後に\"=\"がありませんでした"

#: fe-connect.c:5454 fe-connect.c:6090 fe-connect.c:6888
#, c-format
msgid "invalid connection option \"%s\""
msgstr "不正な接続オプション\"%s\""

#: fe-connect.c:5469 fe-connect.c:5955
#, c-format
msgid "unterminated quoted string in connection info string"
msgstr "接続情報文字列内の閉じていない引用符"

#: fe-connect.c:5549
#, c-format
msgid "definition of service \"%s\" not found"
msgstr "サービス定義\"%s\"がみつかりません"

#: fe-connect.c:5575
#, c-format
msgid "service file \"%s\" not found"
msgstr "サービスファイル\"%s\"がみつかりません"

#: fe-connect.c:5588
#, c-format
msgid "line %d too long in service file \"%s\""
msgstr "サービスファイル\"%2$s\"の行%1$dが長すぎます"

#: fe-connect.c:5659 fe-connect.c:5702
#, c-format
msgid "syntax error in service file \"%s\", line %d"
msgstr "サービスファイル\"%s\"の行%dで構文エラー"

#: fe-connect.c:5670
#, c-format
msgid "nested service specifications not supported in service file \"%s\", line %d"
msgstr "サービスファイル\"%s\"、行%dでのネストしたサービス指定はサポートされていません"

#: fe-connect.c:6409
#, c-format
msgid "invalid URI propagated to internal parser routine: \"%s\""
msgstr "内部パーサ処理へ伝播した不正なURI: \"%s\""

#: fe-connect.c:6486
#, c-format
msgid "end of string reached when looking for matching \"]\" in IPv6 host address in URI: \"%s\""
msgstr "URI \"%s\"内のIPv6ホストアドレスにおいて対応する\"]\"を探している間に文字列が終わりました"

#: fe-connect.c:6493
#, c-format
msgid "IPv6 host address may not be empty in URI: \"%s\""
msgstr "URI内ではIPv6ホストアドレスは空であってはなりません: \"%s\""

#: fe-connect.c:6508
#, c-format
msgid "unexpected character \"%c\" at position %d in URI (expected \":\" or \"/\"): \"%s\""
msgstr "URI内の位置%2$dに想定外の文字\"%1$c\"があります(\":\"または\"/\"を期待していました): \"%3$s\""

#: fe-connect.c:6637
#, c-format
msgid "extra key/value separator \"=\" in URI query parameter: \"%s\""
msgstr "URI問い合わせパラメータ内にキーと値を分ける\"=\"が余分にあります: \"%s\""

#: fe-connect.c:6657
#, c-format
msgid "missing key/value separator \"=\" in URI query parameter: \"%s\""
msgstr "URI問い合わせパラメータ内にキーと値を分ける\\\"=\\\"がありません: \"%s\""

#: fe-connect.c:6709
#, c-format
msgid "invalid URI query parameter: \"%s\""
msgstr "不正なURI問い合わせパラメータ:\"%s\""

#: fe-connect.c:6783
#, c-format
msgid "invalid percent-encoded token: \"%s\""
msgstr "不正なパーセント符号化トークン: \"%s\""

#: fe-connect.c:6793
#, c-format
msgid "forbidden value %%00 in percent-encoded value: \"%s\""
msgstr "パーセント符号化された値では値%%00は許されません: \"%s\""

#: fe-connect.c:7157
msgid "connection pointer is NULL\n"
msgstr "接続ポインタはNULLです\n"

#: fe-connect.c:7165 fe-exec.c:713 fe-exec.c:975 fe-exec.c:3459
#: fe-protocol3.c:991 fe-protocol3.c:1024
msgid "out of memory\n"
msgstr "メモリ不足\n"

#: fe-connect.c:7456
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "WARNING: password file \"%s\" is not a plain file\n"
msgstr "WARNING: パスワードファイル\"%s\"がテキストファイルではありません\n"

<<<<<<< HEAD
#: fe-connect.c:6512
=======
#: fe-connect.c:7465
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "WARNING: password file \"%s\" has group or world access; permissions should be u=rw (0600) or less\n"
msgstr "警告: パスワードファイル \"%s\" がグループメンバもしくは他のユーザーから読める状態になっています。この権限はu=rw (0600)以下にすべきです\n"

<<<<<<< HEAD
#: fe-connect.c:6606
=======
#: fe-connect.c:7572
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "password retrieved from file \"%s\""
msgstr "パスワードはファイル\"%s\"から取り出しました"

<<<<<<< HEAD
#: fe-exec.c:437 fe-exec.c:2779
=======
#: fe-connect.c:7724
#, c-format
msgid "invalid integer value \"%s\" for connection option \"%s\""
msgstr "接続オプション\"%2$s\"に対する不正な整数値\"%1$s\""

#: fe-exec.c:469 fe-exec.c:3533
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "row number %d is out of range 0..%d"
msgstr "行番号%dは0..%dの範囲を超えています"

<<<<<<< HEAD
#: fe-exec.c:498 fe-protocol2.c:502 fe-protocol2.c:537 fe-protocol2.c:1056
#: fe-protocol3.c:208 fe-protocol3.c:235 fe-protocol3.c:252 fe-protocol3.c:332
#: fe-protocol3.c:727 fe-protocol3.c:958
msgid "out of memory"
msgstr "メモリ不足です"

#: fe-exec.c:499 fe-protocol2.c:1402 fe-protocol3.c:1893
=======
#: fe-exec.c:531 fe-protocol3.c:1993
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s"
msgstr "%s"

<<<<<<< HEAD
#: fe-exec.c:847
msgid "NOTICE"
msgstr "注意"

#: fe-exec.c:905
msgid "PGresult cannot support more than INT_MAX tuples"
msgstr "PGresultはINT_MAX個以上のタプルを扱えません"

#: fe-exec.c:917
msgid "size_t overflow"
msgstr "size_t オーバーフロー"

#: fe-exec.c:1192 fe-exec.c:1250 fe-exec.c:1296
msgid "command string is a null pointer\n"
msgstr "コマンド文字列がヌルポインタです\n"

#: fe-exec.c:1256 fe-exec.c:1302 fe-exec.c:1397
msgid "number of parameters must be between 0 and 65535\n"
msgstr "パラメータ数は0から65535まででなければなりません\n"

#: fe-exec.c:1290 fe-exec.c:1391
msgid "statement name is a null pointer\n"
msgstr "文の名前がヌルポインタです\n"

#: fe-exec.c:1310 fe-exec.c:1473 fe-exec.c:2191 fe-exec.c:2393
msgid "function requires at least protocol version 3.0\n"
msgstr "関数は少なくともプロトコルバージョン3.0が必要です\n"

#: fe-exec.c:1428
msgid "no connection to the server\n"
msgstr "サーバへの接続がありません\n"

#: fe-exec.c:1435
msgid "another command is already in progress\n"
msgstr "他のコマンドを処理しています\n"

#: fe-exec.c:1549
msgid "length must be given for binary parameter\n"
msgstr "バイナリパラメータには長さを指定しなければなりません\n"

#: fe-exec.c:1821
#, c-format
msgid "unexpected asyncStatus: %d\n"
msgstr "想定外のasyncStatus: %d\n"

#: fe-exec.c:1841
#, c-format
msgid "PGEventProc \"%s\" failed during PGEVT_RESULTCREATE event\n"
msgstr "PGEVT_RESULTCREATEイベント中にPGEventProc \"%s\"に失敗しました\n"

#: fe-exec.c:2001
msgid "COPY terminated by new PQexec"
msgstr "新たなPQexec\"によりCOPYが終了しました"

#: fe-exec.c:2009
msgid "COPY IN state must be terminated first\n"
msgstr "まずCOPY IN状態を終了させなければなりません\n"

#: fe-exec.c:2029
msgid "COPY OUT state must be terminated first\n"
msgstr "まずCOPY OUT状態を終了させなければなりません\n"

#: fe-exec.c:2037
msgid "PQexec not allowed during COPY BOTH\n"
msgstr "COPY BOTH 実行中の PQexec は許可されていません\n"

#: fe-exec.c:2283 fe-exec.c:2350 fe-exec.c:2440 fe-protocol2.c:1359
#: fe-protocol3.c:1824
msgid "no COPY in progress\n"
msgstr "実行中のCOPYはありません\n"

#: fe-exec.c:2630
msgid "connection in wrong state\n"
msgstr "接続状態が異常です\n"

#: fe-exec.c:2661
msgid "invalid ExecStatusType code"
msgstr "ExecStatusTypeコードが不正です"

#: fe-exec.c:2688
msgid "PGresult is not an error result\n"
msgstr "PGresutがエラー結果ではありません\n"

#: fe-exec.c:2763 fe-exec.c:2786
#, c-format
msgid "column number %d is out of range 0..%d"
msgstr "列番号%dは0..%dの範囲を超えています"

#: fe-exec.c:2801
#, c-format
msgid "parameter number %d is out of range 0..%d"
msgstr "パラメータ%dは0..%dの範囲を超えています"

#: fe-exec.c:3111
#, c-format
msgid "could not interpret result from server: %s"
msgstr "サーバからの結果を解釈できませんでした: %s"

#: fe-exec.c:3350 fe-exec.c:3434
msgid "incomplete multibyte character\n"
msgstr "不完全なマルチバイト文字\n"

#: fe-lobj.c:154
msgid "cannot determine OID of function lo_truncate\n"
msgstr "lo_truncate関数のOIDを決定できません\n"

#: fe-lobj.c:170
msgid "argument of lo_truncate exceeds integer range\n"
msgstr "lo_truncateへの引数が整数範囲を超えています。\n"

#: fe-lobj.c:221
msgid "cannot determine OID of function lo_truncate64\n"
msgstr "lo_truncate64関数のOIDを決定できません\n"

#: fe-lobj.c:279
msgid "argument of lo_read exceeds integer range\n"
msgstr "lo_readへの引数が整数範囲を超えています。\n"

#: fe-lobj.c:334
msgid "argument of lo_write exceeds integer range\n"
msgstr "lo_writeへの引数が整数範囲を超えています。\n"

#: fe-lobj.c:425
msgid "cannot determine OID of function lo_lseek64\n"
msgstr "lo_lseek64関数のOIDを決定できません\n"

#: fe-lobj.c:521
msgid "cannot determine OID of function lo_create\n"
msgstr "lo_create関数のOIDを決定できません\n"

#: fe-lobj.c:600
msgid "cannot determine OID of function lo_tell64\n"
msgstr "lo_tell64関数のOIDを決定できません\n"

#: fe-lobj.c:706 fe-lobj.c:815
#, c-format
msgid "could not open file \"%s\": %s\n"
msgstr "ファイル\"%s\"をオープンできませんでした: %s\n"

#: fe-lobj.c:761
#, c-format
msgid "could not read from file \"%s\": %s\n"
msgstr "ファイル\"%s\"を読み込めませんでした: %s\n"

#: fe-lobj.c:835 fe-lobj.c:859
#, c-format
msgid "could not write to file \"%s\": %s\n"
msgstr "ファイル\"%s\"に書き込めませんでした: %s\n"

#: fe-lobj.c:946
msgid "query to initialize large object functions did not return data\n"
msgstr "ラージオブジェクト機能を初期化する問い合わせがデータを返しませんでした\n"

#: fe-lobj.c:995
msgid "cannot determine OID of function lo_open\n"
msgstr "lo_open関数のOIDを決定できません\n"

#: fe-lobj.c:1002
msgid "cannot determine OID of function lo_close\n"
msgstr "lo_close関数のOIDを決定できません\n"

#: fe-lobj.c:1009
msgid "cannot determine OID of function lo_creat\n"
msgstr "lo_creat関数のOIDを決定できません\n"

#: fe-lobj.c:1016
msgid "cannot determine OID of function lo_unlink\n"
msgstr "lo_unlink関数のOIDを決定できません\n"

#: fe-lobj.c:1023
msgid "cannot determine OID of function lo_lseek\n"
msgstr "lo_lseek関数のOIDを決定できません\n"

#: fe-lobj.c:1030
msgid "cannot determine OID of function lo_tell\n"
msgstr "lo_tell関数のOIDを決定できません\n"

#: fe-lobj.c:1037
msgid "cannot determine OID of function loread\n"
msgstr "loread関数のOIDを決定できません\n"

#: fe-lobj.c:1044
msgid "cannot determine OID of function lowrite\n"
msgstr "lowrite関数のOIDを決定できません\n"

#: fe-misc.c:290
#, c-format
msgid "integer of size %lu not supported by pqGetInt"
msgstr "サイズ%luの整数はpqGetIntでサポートされていません"

#: fe-misc.c:326
#, c-format
msgid "integer of size %lu not supported by pqPutInt"
msgstr "サイズ%luの整数はpqPutIntでサポートされていません"

#: fe-misc.c:637 fe-misc.c:838
msgid "connection not open\n"
msgstr "接続はオープンされていません\n"

#: fe-misc.c:807 fe-secure-openssl.c:206 fe-secure-openssl.c:314
#: fe-secure.c:261 fe-secure.c:371
msgid ""
"server closed the connection unexpectedly\n"
"\tThis probably means the server terminated abnormally\n"
"\tbefore or while processing the request.\n"
msgstr ""
"サーバとの接続が想定外にクローズされました\n"
"        おそらく要求の処理前または処理中にサーバが異常終了\n"
"        したことを意味しています。\n"

#: fe-misc.c:1009
msgid "timeout expired\n"
msgstr "タイムアウト期間が過ぎました\n"

#: fe-misc.c:1054
msgid "invalid socket\n"
msgstr "不正なソケットです\n"

#: fe-misc.c:1077
#, c-format
msgid "select() failed: %s\n"
msgstr "select()が失敗しました: %s\n"

#: fe-protocol2.c:90
#, c-format
msgid "invalid setenv state %c, probably indicative of memory corruption\n"
msgstr "setenv状態%cは不正です。メモリ障害の可能性があります\n"

#: fe-protocol2.c:389
#, c-format
msgid "invalid state %c, probably indicative of memory corruption\n"
msgstr "状態%cは不正です。メモリ障害の可能性があります\n"

#: fe-protocol2.c:478 fe-protocol3.c:185
#, c-format
msgid "message type 0x%02x arrived from server while idle"
msgstr "待機中にサーバからメッセージ種類0x%02xが届きました"

#: fe-protocol2.c:528
#, c-format
msgid "unexpected character %c following empty query response (\"I\" message)"
msgstr "空の問い合わせ応答(\"I\"メッセージ)の後に想定外の文字%cがありました"

#: fe-protocol2.c:594
#, c-format
msgid "server sent data (\"D\" message) without prior row description (\"T\" message)"
msgstr "サーバが事前の行記述(\"T\"メッセージ)なしにデータ(\"D\"メッセージ)を送信しました"

#: fe-protocol2.c:612
#, c-format
msgid "server sent binary data (\"B\" message) without prior row description (\"T\" message)"
msgstr "サーバが事前の行記述(\"T\"メッセージ)なしにバイナリデータ(\"B\"メッセージ)を送信しました"

#: fe-protocol2.c:632 fe-protocol3.c:411
#, c-format
msgid "unexpected response from server; first received character was \"%c\"\n"
msgstr "サーバから想定外の応答がありました。受け付けた先頭文字は\"%c\"です\n"

#: fe-protocol2.c:761 fe-protocol2.c:936 fe-protocol3.c:626 fe-protocol3.c:853
msgid "out of memory for query result"
msgstr "問い合わせ結果用のメモリが不足しています"

#: fe-protocol2.c:1414
=======
#: fe-exec.c:834
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "write to server failed"
msgstr "サーバーへの書き込みに失敗"

<<<<<<< HEAD
#: fe-protocol2.c:1548 fe-protocol2.c:1580 fe-protocol3.c:2096
=======
#: fe-exec.c:874
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "no error text available"
msgstr "エラー文字列がありません"

<<<<<<< HEAD
#: fe-protocol3.c:367
msgid "server sent data (\"D\" message) without prior row description (\"T\" message)\n"
msgstr "サーバが事前の行記述(\"T\"メッセージ)なしにデータ(\"D\"メッセージ)を送信しました\"\n"

#: fe-protocol3.c:432
=======
#: fe-exec.c:963
msgid "NOTICE"
msgstr "注意"

#: fe-exec.c:1021
msgid "PGresult cannot support more than INT_MAX tuples"
msgstr "PGresultはINT_MAX個以上のタプルを扱えません"

#: fe-exec.c:1033
msgid "size_t overflow"
msgstr "size_t オーバーフロー"

#: fe-exec.c:1438 fe-exec.c:1507 fe-exec.c:1553
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "command string is a null pointer"
msgstr "コマンド文字列がヌルポインタです"

<<<<<<< HEAD
#: fe-protocol3.c:453
=======
#: fe-exec.c:1444 fe-exec.c:3003
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s not allowed in pipeline mode"
msgstr "%sはパイプラインモードでは使用できません"

<<<<<<< HEAD
#: fe-protocol3.c:504 fe-protocol3.c:544
msgid "insufficient data in \"T\" message"
msgstr "\"T\"メッセージ内のデータが不十分です"

#: fe-protocol3.c:577
msgid "extraneous data in \"T\" message"
msgstr "\"T\"メッセージ内に無関係なデータがあります"

#: fe-protocol3.c:690
msgid "extraneous data in \"t\" message"
msgstr "\"t\"メッセージ内に無関係なデータがあります"

#: fe-protocol3.c:761 fe-protocol3.c:793 fe-protocol3.c:811
msgid "insufficient data in \"D\" message"
msgstr "\"D\"\"メッセージ内のデータが不十分です"

#: fe-protocol3.c:767
msgid "unexpected field count in \"D\" message"
msgstr "\"D\"メッセージ内のフィールド数が想定外です。"

#: fe-protocol3.c:820
msgid "extraneous data in \"D\" message"
msgstr "”D\"メッセージ内に無関係なデータがあります"

#: fe-protocol3.c:1012
=======
#: fe-exec.c:1512 fe-exec.c:1558 fe-exec.c:1652
#, c-format
msgid "number of parameters must be between 0 and %d"
msgstr "パラメータ数は0から%dまでの間でなければなりません"

#: fe-exec.c:1548 fe-exec.c:1647
#, c-format
msgid "statement name is a null pointer"
msgstr "文の名前がヌルポインタです"

#: fe-exec.c:1689 fe-exec.c:3379
#, c-format
msgid "no connection to the server"
msgstr "サーバーへの接続がありません"

#: fe-exec.c:1697 fe-exec.c:3387
#, c-format
msgid "another command is already in progress"
msgstr "他のコマンドがすでに処理中です"

#: fe-exec.c:1727
#, c-format
msgid "cannot queue commands during COPY"
msgstr "COPY中はコマンドのキューイングはできません"

#: fe-exec.c:1846
#, c-format
msgid "length must be given for binary parameter"
msgstr "バイナリパラメータには長さを指定する必要があります"

#: fe-exec.c:2205
#, c-format
msgid "unexpected asyncStatus: %d"
msgstr "想定外のasyncStatus: %d"

#: fe-exec.c:2361
#, c-format
msgid "synchronous command execution functions are not allowed in pipeline mode"
msgstr "同期的にコマンドを実行する関数はパイプラインモード中は実行できません"

#: fe-exec.c:2378
msgid "COPY terminated by new PQexec"
msgstr "新たなPQexec\"によりCOPYが終了しました"

#: fe-exec.c:2394
#, c-format
msgid "PQexec not allowed during COPY BOTH"
msgstr "COPY BOTH 実行中の PQexec は許可されていません"

#: fe-exec.c:2630
#, c-format
msgid "unrecognized message type \"%c\""
msgstr "認識できないメッセージタイプ\"%c\""

#: fe-exec.c:2702 fe-exec.c:2756 fe-exec.c:2824 fe-protocol3.c:1924
#, c-format
msgid "no COPY in progress"
msgstr "実行中のCOPYはありません"

#: fe-exec.c:3010
#, c-format
msgid "connection in wrong state"
msgstr "接続状態が異常です"

#: fe-exec.c:3053
#, c-format
msgid "cannot enter pipeline mode, connection not idle"
msgstr "パイプラインモードに入れません、接続がアイドル状態ではありません"

#: fe-exec.c:3089 fe-exec.c:3110
#, c-format
msgid "cannot exit pipeline mode with uncollected results"
msgstr "未回収の結果が残っている状態でパイプラインモードを抜けることはできません"

#: fe-exec.c:3093
#, c-format
msgid "cannot exit pipeline mode while busy"
msgstr "ビジー状態でパイプラインモードを抜けることはできません"

#: fe-exec.c:3104
#, c-format
msgid "cannot exit pipeline mode while in COPY"
msgstr "COPY実行中にパイプラインモードを抜けることはできません"

#: fe-exec.c:3303
#, c-format
msgid "cannot send pipeline when not in pipeline mode"
msgstr "パイプラインモード外でパイプライン送出はできません"

#: fe-exec.c:3422
msgid "invalid ExecStatusType code"
msgstr "ExecStatusTypeコードが不正です"

#: fe-exec.c:3449
msgid "PGresult is not an error result\n"
msgstr "PGresutがエラー結果ではありません\n"

#: fe-exec.c:3517 fe-exec.c:3540
#, c-format
msgid "column number %d is out of range 0..%d"
msgstr "列番号%dは0..%dの範囲を超えています"

#: fe-exec.c:3555
#, c-format
msgid "parameter number %d is out of range 0..%d"
msgstr "パラメータ%dは0..%dの範囲を超えています"

#: fe-exec.c:3866
#, c-format
msgid "could not interpret result from server: %s"
msgstr "サーバーからの結果を解釈できませんでした: %s"

#: fe-exec.c:4127 fe-exec.c:4217
#, c-format
msgid "incomplete multibyte character"
msgstr "不完全なマルチバイト文字"

#: fe-gssapi-common.c:122
msgid "GSSAPI name import error"
msgstr "GSSAPI名のインポートエラー"

#: fe-lobj.c:144 fe-lobj.c:207 fe-lobj.c:397 fe-lobj.c:487 fe-lobj.c:560
#: fe-lobj.c:956 fe-lobj.c:963 fe-lobj.c:970 fe-lobj.c:977 fe-lobj.c:984
#: fe-lobj.c:991 fe-lobj.c:998 fe-lobj.c:1005
#, c-format
msgid "cannot determine OID of function %s"
msgstr "関数%sのOIDが特定できません"

#: fe-lobj.c:160
#, c-format
msgid "argument of lo_truncate exceeds integer range"
msgstr "lo_truncateの引数が整数の範囲を超えています"

#: fe-lobj.c:262
#, c-format
msgid "argument of lo_read exceeds integer range"
msgstr "lo_readの引数が整数の範囲を超えています"

#: fe-lobj.c:313
#, c-format
msgid "argument of lo_write exceeds integer range"
msgstr "lo_writeの引数が整数範囲を超えています"

#: fe-lobj.c:669 fe-lobj.c:780
#, c-format
msgid "could not open file \"%s\": %s"
msgstr "ファイル\"%s\"をオープンできませんでした: %s"

#: fe-lobj.c:725
#, c-format
msgid "could not read from file \"%s\": %s"
msgstr "ファイル\"%s\"を読み込めませんでした: %s"

#: fe-lobj.c:801 fe-lobj.c:824
#, c-format
msgid "could not write to file \"%s\": %s"
msgstr "ファイル\"%s\"に書き込めませんでした: %s"

#: fe-lobj.c:908
#, c-format
msgid "query to initialize large object functions did not return data"
msgstr "ラージオブジェクト機能を初期化する問い合わせがデータを返しませんでした"

#: fe-misc.c:239
#, c-format
msgid "integer of size %lu not supported by pqGetInt"
msgstr "サイズ%luの整数はpqGetIntでサポートされていません"

#: fe-misc.c:272
#, c-format
msgid "integer of size %lu not supported by pqPutInt"
msgstr "サイズ%luの整数はpqPutIntでサポートされていません"

#: fe-misc.c:750 fe-secure-openssl.c:203 fe-secure-openssl.c:309
#: fe-secure.c:237 fe-secure.c:404
#, c-format
msgid ""
"server closed the connection unexpectedly\n"
"\tThis probably means the server terminated abnormally\n"
"\tbefore or while processing the request."
msgstr ""
"サーバーとの接続が想定外にクローズされました\n"
"        おそらく要求の処理前または処理中にサーバーが異常終了\n"
"        したことを意味しています。"

#: fe-misc.c:817
msgid "connection not open\n"
msgstr "接続はオープンされていません\n"

#: fe-misc.c:1005
#, c-format
msgid "timeout expired"
msgstr "タイムアウト期間が過ぎました"

#: fe-misc.c:1049
#, c-format
msgid "invalid socket"
msgstr "不正なソケットです"

#: fe-misc.c:1071
#, c-format
msgid "%s() failed: %s"
msgstr "%s() が失敗しました: %s"

#: fe-protocol3.c:187
#, c-format
msgid "message type 0x%02x arrived from server while idle"
msgstr "待機中にサーバーからメッセージ種類0x%02xが届きました"

#: fe-protocol3.c:402
#, c-format
msgid "server sent data (\"D\" message) without prior row description (\"T\" message)"
msgstr "サーバーが先行の行記述(\"T\"メッセージ)なしでデータ(\"D\"メッセージ)を送信しました"

#: fe-protocol3.c:444
#, c-format
msgid "unexpected response from server; first received character was \"%c\""
msgstr "サーバーから想定外の応答がありました。受け付けた先頭文字は\"%c\"です"

#: fe-protocol3.c:467
#, c-format
msgid "message contents do not agree with length in message type \"%c\""
msgstr "メッセージの内容がメッセージタイプ\"%c\"での長さと合っていません"

#: fe-protocol3.c:485
#, c-format
msgid "lost synchronization with server: got message type \"%c\", length %d"
msgstr "サーバーとの同期が失われました。受信したメッセージタイプは\"%c\"、長さは%d"

#: fe-protocol3.c:537 fe-protocol3.c:577
msgid "insufficient data in \"T\" message"
msgstr "\"T\"メッセージ内のデータが不十分です"

#: fe-protocol3.c:648 fe-protocol3.c:854
msgid "out of memory for query result"
msgstr "問い合わせ結果用のメモリが不足しています"

#: fe-protocol3.c:717
msgid "insufficient data in \"t\" message"
msgstr "\"t\"メッセージ内のデータが足りません"

#: fe-protocol3.c:776 fe-protocol3.c:808 fe-protocol3.c:826
msgid "insufficient data in \"D\" message"
msgstr "\"D\"\"メッセージ内のデータが不十分です"

#: fe-protocol3.c:782
msgid "unexpected field count in \"D\" message"
msgstr "\"D\"メッセージ内のフィールド数が想定外です。"

#: fe-protocol3.c:1037
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
msgid "no error message available\n"
msgstr "エラーメッセージがありません\n"

#. translator: %s represents a digit string
<<<<<<< HEAD
#: fe-protocol3.c:1042 fe-protocol3.c:1061
=======
#: fe-protocol3.c:1085 fe-protocol3.c:1104
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid " at character %s"
msgstr "(文字位置: %s)"

<<<<<<< HEAD
#: fe-protocol3.c:1074
=======
#: fe-protocol3.c:1117
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "DETAIL:  %s\n"
msgstr "DETAIL:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1077
=======
#: fe-protocol3.c:1120
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "HINT:  %s\n"
msgstr "HINT:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1080
=======
#: fe-protocol3.c:1123
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "QUERY:  %s\n"
msgstr "QUERY:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1087
=======
#: fe-protocol3.c:1130
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "CONTEXT:  %s\n"
msgstr "CONTEXT:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1096
=======
#: fe-protocol3.c:1139
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SCHEMA NAME:  %s\n"
msgstr "SCHEMA NAME:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1100
=======
#: fe-protocol3.c:1143
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "TABLE NAME:  %s\n"
msgstr "TABLE NAME:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1104
=======
#: fe-protocol3.c:1147
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "COLUMN NAME:  %s\n"
msgstr "COLUMN NAME:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1108
=======
#: fe-protocol3.c:1151
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "DATATYPE NAME:  %s\n"
msgstr "DATATYPE NAME:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1112
=======
#: fe-protocol3.c:1155
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "CONSTRAINT NAME:  %s\n"
msgstr "CONSTRAINT NAME:  %s\n"

<<<<<<< HEAD
#: fe-protocol3.c:1124
msgid "LOCATION:  "
msgstr "LOCATION:  "

#: fe-protocol3.c:1126
=======
#: fe-protocol3.c:1167
msgid "LOCATION:  "
msgstr "LOCATION:  "

#: fe-protocol3.c:1169
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s, "
msgstr "%s, "

<<<<<<< HEAD
#: fe-protocol3.c:1128
=======
#: fe-protocol3.c:1171
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s:%s"
msgstr "%s:%s"

<<<<<<< HEAD
#: fe-protocol3.c:1323
=======
#: fe-protocol3.c:1366
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "LINE %d: "
msgstr "行 %d: "

<<<<<<< HEAD
#: fe-protocol3.c:1718
msgid "PQgetline: not doing text COPY OUT\n"
msgstr "PQgetline: テキストのCOPY OUTを行っていません\n"

#: fe-secure-common.c:124
msgid "SSL certificate's name contains embedded null\n"
msgstr "SSL証明書の名前の途中にnullが含まれています\n"

#: fe-secure-common.c:171
msgid "host name must be specified for a verified SSL connection\n"
msgstr "SSL 接続を検証するためにホスト名を指定しなければなりません\n"

#: fe-secure-common.c:196
#, c-format
msgid "server certificate for \"%s\" does not match host name \"%s\"\n"
msgstr "\"%s\"のサーバ証明書がホスト名\"%s\"とマッチしません\n"

#: fe-secure-common.c:202
msgid "could not get server's host name from server certificate\n"
msgstr "サーバ証明書からサーバのホスト名を取り出すことができませんでした。\n"

#: fe-secure-openssl.c:211 fe-secure-openssl.c:319 fe-secure-openssl.c:1219
=======
#: fe-protocol3.c:1440
#, c-format
msgid "protocol version not supported by server: client uses %u.%u, server supports up to %u.%u"
msgstr "サーバーはこのプロトコルバージョンをサポートしていません。クライアントは%u.%uを使用、 サーバーは%u.%uまでをサポートします"

#: fe-protocol3.c:1446
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "protocol extension not supported by server: %s"
msgid_plural "protocol extensions not supported by server: %s"
msgstr[0] "サーバーでサポートされていないプロトコル拡張: %s"

<<<<<<< HEAD
#: fe-secure-openssl.c:218 fe-secure-openssl.c:326 fe-secure-openssl.c:1223
msgid "SSL SYSCALL error: EOF detected\n"
msgstr "SSL SYSCALLエラー: EOFを検知\n"

#: fe-secure-openssl.c:229 fe-secure-openssl.c:337 fe-secure-openssl.c:1232
=======
#: fe-protocol3.c:1454
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "invalid %s message"
msgstr "不正な%sメッセージ"

<<<<<<< HEAD
#: fe-secure-openssl.c:244 fe-secure-openssl.c:352
msgid "SSL connection has been closed unexpectedly\n"
msgstr "SSL接続が意図せずにクローズされました\n"

#: fe-secure-openssl.c:250 fe-secure-openssl.c:358 fe-secure-openssl.c:1241
=======
#: fe-protocol3.c:1819
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PQgetline: not doing text COPY OUT"
msgstr "PQgetline: テキストのCOPY OUTを行っていません"

<<<<<<< HEAD
#: fe-secure-openssl.c:398
msgid "could not determine server certificate signature algorithm\n"
msgstr "サーバ証明書の署名アルゴリズムを決定できませんでした\n"

#: fe-secure-openssl.c:419
#, c-format
msgid "could not find digest for NID %s\n"
msgstr "NID %sのダイジェストが見つかりませんでした\n"

#: fe-secure-openssl.c:429
msgid "could not generate peer certificate hash\n"
msgstr "ピアの証明書ハッシュの生成に失敗しました\n"

#: fe-secure-openssl.c:486
msgid "SSL certificate's name entry is missing\n"
msgstr "SSL証明書に名前の項目がありません\n"

#: fe-secure-openssl.c:815
=======
#: fe-protocol3.c:2193
#, c-format
msgid "protocol error: no function result"
msgstr "プロトコルエラー: 関数の結果がありません"

#: fe-protocol3.c:2204
#, c-format
msgid "protocol error: id=0x%x"
msgstr "プロトコルエラー: id=0x%x"

#: fe-secure-common.c:123
#, c-format
msgid "SSL certificate's name contains embedded null"
msgstr "SSL証明書の名前の途中にnullが含まれています"

#: fe-secure-common.c:228
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "certificate contains IP address with invalid length %zu"
msgstr "証明書は不正な長さ%zuのIPアドレスを含んでいます"

<<<<<<< HEAD
#: fe-secure-openssl.c:852
=======
#: fe-secure-common.c:237
#, c-format
msgid "could not convert certificate's IP address to string: %s"
msgstr "証明書のIPアドレスを文字列へ変換できませんでした: %s"

#: fe-secure-common.c:269
#, c-format
msgid "host name must be specified for a verified SSL connection"
msgstr "検証SSL接続ではホスト名を指定しなければなりません"

#: fe-secure-common.c:286
#, c-format
msgid "server certificate for \"%s\" (and %d other name) does not match host name \"%s\""
msgid_plural "server certificate for \"%s\" (and %d other names) does not match host name \"%s\""
msgstr[0] "\"%s\"のサーバー証明書(および%d個のほかの名前)はホスト名\"%s\"と一致しません"

#: fe-secure-common.c:294
#, c-format
msgid "server certificate for \"%s\" does not match host name \"%s\""
msgstr "\"%s\"のサーバー証明書がホスト名\"%s\"とマッチしません"

#: fe-secure-common.c:299
#, c-format
msgid "could not get server's host name from server certificate"
msgstr "サーバー証明書からサーバーのホスト名を取得できませんでした"

#: fe-secure-gssapi.c:194
msgid "GSSAPI wrap error"
msgstr "GSSAPI名ラップエラー"

#: fe-secure-gssapi.c:201
#, c-format
msgid "outgoing GSSAPI message would not use confidentiality"
msgstr "送出されるGSSAPIメッセージに機密性が適用されません"

#: fe-secure-gssapi.c:208
#, c-format
msgid "client tried to send oversize GSSAPI packet (%zu > %zu)"
msgstr "クライアントは過大なGSSAPIパケットを送信しようとしました: (%zu > %zu)"

#: fe-secure-gssapi.c:347 fe-secure-gssapi.c:589
#, c-format
msgid "oversize GSSAPI packet sent by the server (%zu > %zu)"
msgstr "過大なGSSAPIパケットがサーバーから送出されました: (%zu > %zu)"

#: fe-secure-gssapi.c:386
msgid "GSSAPI unwrap error"
msgstr "GSSAPIアンラップエラー"

#: fe-secure-gssapi.c:395
#, c-format
msgid "incoming GSSAPI message did not use confidentiality"
msgstr "到着したGSSAPIメッセージには機密性が適用されていません"

#: fe-secure-gssapi.c:652
msgid "could not initiate GSSAPI security context"
msgstr "GSSAPIセキュリティコンテキストを開始できませんでした"

#: fe-secure-gssapi.c:681
msgid "GSSAPI size check error"
msgstr "GSSAPIサイズチェックエラー"

#: fe-secure-gssapi.c:692
msgid "GSSAPI context establishment error"
msgstr "GSSAPIコンテクスト確立エラー"

#: fe-secure-openssl.c:207 fe-secure-openssl.c:313 fe-secure-openssl.c:1524
#, c-format
msgid "SSL SYSCALL error: %s"
msgstr "SSL SYSCALLエラー: %s"

#: fe-secure-openssl.c:213 fe-secure-openssl.c:319 fe-secure-openssl.c:1527
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SSL SYSCALL error: EOF detected"
msgstr "SSL SYSCALLエラー: EOFを検出"

<<<<<<< HEAD
#: fe-secure-openssl.c:880
=======
#: fe-secure-openssl.c:223 fe-secure-openssl.c:329 fe-secure-openssl.c:1535
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SSL error: %s"
msgstr "SSLエラー: %s"

<<<<<<< HEAD
#: fe-secure-openssl.c:908
=======
#: fe-secure-openssl.c:237 fe-secure-openssl.c:343
#, c-format
msgid "SSL connection has been closed unexpectedly"
msgstr "SSL接続が意図せずにクローズされました"

#: fe-secure-openssl.c:242 fe-secure-openssl.c:348 fe-secure-openssl.c:1582
#, c-format
msgid "unrecognized SSL error code: %d"
msgstr "認識できないSSLエラーコード: %d"

#: fe-secure-openssl.c:390
#, c-format
msgid "could not determine server certificate signature algorithm"
msgstr "サーバー証明書の署名アルゴリズムを特定できませんでした"

#: fe-secure-openssl.c:410
#, c-format
msgid "could not find digest for NID %s"
msgstr "NID %sのダイジェストが見つかりませんでした"

#: fe-secure-openssl.c:419
#, c-format
msgid "could not generate peer certificate hash"
msgstr "接続先の証明書ハッシュの生成に失敗しました"

#: fe-secure-openssl.c:501
#, c-format
msgid "SSL certificate's name entry is missing"
msgstr "SSL証明書に名前のエントリがありません"

#: fe-secure-openssl.c:535
#, c-format
msgid "SSL certificate's address entry is missing"
msgstr "SSL証明書のアドレスのエントリがありません"

#: fe-secure-openssl.c:935
#, c-format
msgid "could not create SSL context: %s"
msgstr "SSLコンテキストを作成できませんでした: %s"

#: fe-secure-openssl.c:977
#, c-format
msgid "invalid value \"%s\" for minimum SSL protocol version"
msgstr "SSLプロトコル最小バージョンに対する不正な値\"%s\""

#: fe-secure-openssl.c:987
#, c-format
msgid "could not set minimum SSL protocol version: %s"
msgstr "SSLプロトコル最小バージョンを設定できませんでした: %s"

#: fe-secure-openssl.c:1003
#, c-format
msgid "invalid value \"%s\" for maximum SSL protocol version"
msgstr "SSLプロトコル最大バージョンに対する不正な値\"%s\""

#: fe-secure-openssl.c:1013
#, c-format
msgid "could not set maximum SSL protocol version: %s"
msgstr "SSLプロトコル最大バージョンを設定できませんでした: %s"

#: fe-secure-openssl.c:1051
#, c-format
msgid "could not load system root certificate paths: %s"
msgstr "システムルート証明書パスをロードできませんでした: %s"

#: fe-secure-openssl.c:1068
#, c-format
msgid "could not read root certificate file \"%s\": %s"
msgstr "ルート証明書ファイル\"%s\"を読み取れませんでした: %s"

#: fe-secure-openssl.c:1120
#, c-format
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
msgid ""
"could not get home directory to locate root certificate file\n"
"Either provide the file, use the system's trusted roots with sslrootcert=system, or change sslmode to disable server certificate verification."
msgstr ""
"ルート証明書ファイルを特定するためのホームディレクトリが取得できませんでした\n"
"ファイルを用意する、 sslrootcert=systemでシステムの信頼済みルート証明書を使用する、または sslmode を変更してサーバー証明書の検証を無効にしてください。"

<<<<<<< HEAD
#: fe-secure-openssl.c:912
=======
#: fe-secure-openssl.c:1123
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid ""
"root certificate file \"%s\" does not exist\n"
"Either provide the file, use the system's trusted roots with sslrootcert=system, or change sslmode to disable server certificate verification."
msgstr ""
"ルート証明書ファイル\"%s\"が存在しません\n"
"ファイルを用意する、sslrootcert=systemでシステムの信頼済みルート証明書を使用する、またはsslmodeを変更してサーバー証明書の検証を無効にしてください。"

<<<<<<< HEAD
#: fe-secure-openssl.c:943
#, c-format
msgid "could not open certificate file \"%s\": %s\n"
msgstr "証明書ファイル\"%s\"をオープンできませんでした: %s\n"

#: fe-secure-openssl.c:962
#, c-format
msgid "could not read certificate file \"%s\": %s\n"
msgstr "証明書ファイル\"%s\"を読み込めませんでした: %s\n"

#: fe-secure-openssl.c:987
#, c-format
msgid "could not establish SSL connection: %s\n"
msgstr "SSL接続を確立できませんでした: %s\n"

#: fe-secure-openssl.c:1041
#, c-format
msgid "could not load SSL engine \"%s\": %s\n"
msgstr "SSLエンジン\"%s\"を読み込みできませんでした: %s\n"

#: fe-secure-openssl.c:1053
#, c-format
msgid "could not initialize SSL engine \"%s\": %s\n"
msgstr "SSLエンジン\"%s\"を初期化できませんでした: %s\n"

#: fe-secure-openssl.c:1069
#, c-format
msgid "could not read private SSL key \"%s\" from engine \"%s\": %s\n"
msgstr "SSL秘密キーファイル\"%s\"をエンジン\"%s\"から読み取れませんでした: %s\n"

#: fe-secure-openssl.c:1083
#, c-format
msgid "could not load private SSL key \"%s\" from engine \"%s\": %s\n"
msgstr "SSL秘密キー\"%s\"をエンジン\"%s\"から読み取れませんでした: %s\n"

#: fe-secure-openssl.c:1120
#, c-format
msgid "certificate present, but not private key file \"%s\"\n"
msgstr "証明書はありましたが、秘密キーファイル\"%s\"はありませんでした\n"

#: fe-secure-openssl.c:1128
#, c-format
msgid "private key file \"%s\" has group or world access; permissions should be u=rw (0600) or less\n"
msgstr "警告：秘密キーファイル \"%s\" がグループメンバや第三者から読める状態になっています。この権限はu=rw (0600)またはそれ以下とすべきです\n"

#: fe-secure-openssl.c:1139
#, c-format
msgid "could not load private key file \"%s\": %s\n"
msgstr "秘密キーファイル\"%s\"をロードできませんでした: %s\n"

#: fe-secure-openssl.c:1153
#, c-format
msgid "certificate does not match private key file \"%s\": %s\n"
msgstr "証明書と秘密キーファイル\"%s\"が一致しません: %s\n"

#: fe-secure-openssl.c:1262
=======
#: fe-secure-openssl.c:1158
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not open certificate file \"%s\": %s"
msgstr "証明書ファイル\"%s\"をオープンできませんでした: %s"

<<<<<<< HEAD
#: fe-secure-openssl.c:1351
=======
#: fe-secure-openssl.c:1176
#, c-format
msgid "could not read certificate file \"%s\": %s"
msgstr "証明書ファイル\"%s\"を読み込めませんでした: %s"

#: fe-secure-openssl.c:1200
#, c-format
msgid "could not establish SSL connection: %s"
msgstr "SSL接続を確立できませんでした: %s"

#: fe-secure-openssl.c:1232
#, c-format
msgid "could not set SSL Server Name Indication (SNI): %s"
msgstr "SSLサーバー名表示(SNI)を設定できませんでした: %s"

#: fe-secure-openssl.c:1249
#, c-format
msgid "could not set SSL ALPN extension: %s"
msgstr "SSL ALPN拡張を設定できませんでした: %s"

#: fe-secure-openssl.c:1292
#, c-format
msgid "could not load SSL engine \"%s\": %s"
msgstr "SSLエンジン\"%s\"を読み込みできませんでした: %s"

#: fe-secure-openssl.c:1303
#, c-format
msgid "could not initialize SSL engine \"%s\": %s"
msgstr "SSLエンジン\"%s\"を初期化できませんでした: %s"

#: fe-secure-openssl.c:1318
#, c-format
msgid "could not read private SSL key \"%s\" from engine \"%s\": %s"
msgstr "SSL秘密鍵\"%s\"をエンジン\"%s\"から読み取れませんでした: %s"

#: fe-secure-openssl.c:1331
#, c-format
msgid "could not load private SSL key \"%s\" from engine \"%s\": %s"
msgstr "SSL秘密鍵\"%s\"をエンジン\"%s\"から読み取れませんでした: %s"

#: fe-secure-openssl.c:1368
#, c-format
msgid "certificate present, but not private key file \"%s\""
msgstr "証明書はありますが、秘密鍵ファイル\"%s\"はありません"

#: fe-secure-openssl.c:1371
#, c-format
msgid "could not stat private key file \"%s\": %m"
msgstr "秘密鍵ファイル\"%s\"をstatできませんでした: %m"

#: fe-secure-openssl.c:1379
#, c-format
msgid "private key file \"%s\" is not a regular file"
msgstr "秘密鍵ファイル\"%s\"は通常のファイルではありません"

#: fe-secure-openssl.c:1412
#, c-format
msgid "private key file \"%s\" has group or world access; file must have permissions u=rw (0600) or less if owned by the current user, or permissions u=rw,g=r (0640) or less if owned by root"
msgstr "秘密鍵ファイル\"%s\"はグループに対して、もしくは無制限にアクセスを許可しています; ファイルのパーミッションは u=rw (0600) かそれよりも狭い必要があります、rootが所有している場合は  u=rw,g=r (0640) かそれよりも狭い必要があります"

#: fe-secure-openssl.c:1436
#, c-format
msgid "could not load private key file \"%s\": %s"
msgstr "秘密鍵ファイル\"%s\"をロードできませんでした: %s"

#: fe-secure-openssl.c:1452
#, c-format
msgid "certificate does not match private key file \"%s\": %s"
msgstr "証明書と秘密鍵ファイル\"%s\"が一致しません: %s"

#: fe-secure-openssl.c:1521
#, c-format
msgid "SSL error: certificate verify failed: %s"
msgstr "SSLエラー: 証明書の検証に失敗しました: %s"

#: fe-secure-openssl.c:1566
#, c-format
msgid "This may indicate that the server does not support any SSL protocol version between %s and %s."
msgstr "このことは、クライアントがSSLプロトコルのバージョン%sから%sの間のいずれもサポートしていないことを示唆しているかもしれません。"

#: fe-secure-openssl.c:1598
#, c-format
msgid "direct SSL connection was established without ALPN protocol negotiation extension"
msgstr "直接SSL接続がALPNプロトコルネゴシエーション拡張なしで確立されました"

#: fe-secure-openssl.c:1610
#, c-format
msgid "SSL connection was established with unexpected ALPN protocol"
msgstr "SSL接続が想定外のALPNプロトコルで確立されました"

#: fe-secure-openssl.c:1627
#, c-format
msgid "certificate could not be obtained: %s"
msgstr "証明書を取得できませんでした: %s"

#: fe-secure-openssl.c:1734
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "no SSL error reported"
msgstr "SSLエラーはありませんでした"

<<<<<<< HEAD
#: fe-secure-openssl.c:1360
=======
#: fe-secure-openssl.c:1776
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SSL error code %lu"
msgstr "SSLエラーコード: %lu"

<<<<<<< HEAD
#: fe-secure.c:269
#, c-format
msgid "could not receive data from server: %s\n"
msgstr "サーバからデータを受信できませんでした: %s\n"

#: fe-secure.c:378
#, c-format
msgid "could not send data to server: %s\n"
msgstr "サーバにデータを送信できませんでした: %s\n"

#: win32.c:317
=======
#: fe-secure-openssl.c:2075
#, c-format
msgid "WARNING: sslpassword truncated\n"
msgstr "警告: sslpasswordが切り詰められました\n"

#: fe-secure.c:248
#, c-format
msgid "could not receive data from server: %s"
msgstr "サーバーからデータを受信できませんでした: %s"

#: fe-secure.c:419
#, c-format
msgid "could not send data to server: %s"
msgstr "サーバーにデータを送信できませんでした: %s"

#: win32.c:310
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "unrecognized socket error: 0x%08X/%d"
msgstr "不明なソケットエラー 0x%08X/%d"
